### ISSUE TITLE
Hint for commits from other forks

### ISSUE THREAD

**Issue by vmario89** [InfernoEmbedded/Deepnest#9]
Hi, 

as ive seen you are trying to maintain a little the project of Jack000. I just clicked through the forks of the project and found some commits which maybe might be copied or pulled into this:

https://github.com/wixdom-projects/Deepnest/commit/d20faa40fa8c15e5c12f14c543a2e5f752e6ce00
https://github.com/PetrPPetrov/Deepnest/commit/a918e968acd4c60f2f34306fea0f5db3167caedb
https://github.com/MPJansen/Deepnest/commits/master

regards, Mario

**Comment by deece** [comment]
Thanks, I'll review these

**Comment by deece** [comment]
I've & merged these, thanks
